[package]
name = "Test"
version = "0.1.0"
authors = ["Filip Bucek <fbucek@invloop.cz>"]
edition = "2018"
workspace = ".."

[dependencies]

[[bin]] 
name="run"
path="src/main.rs"

[lib]
name="test_lib"
path="src/lib.rs"
