name: build

on: [push]

jobs:
  build-linux: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build 
    - name: Run tests
      run: cargo test
